"""initial schema

Revision ID: 88f665e67245
Revises: 
Create Date: 2026-05-10 23:09:20.409580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f665e67245'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('cmc', sa.Float(), nullable=True),
    sa.Column('type_line', sa.String(), nullable=True),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('toughness', sa.String(), nullable=True),
    sa.Column('loyalty', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('is_land', sa.Boolean(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_video_id'), 'games', ['video_id'], unique=True)
    op.create_table('notable_moments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commander_name', sa.String(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('seat_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('active_player_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('life_total', sa.Integer(), nullable=True),
    sa.Column('poison_counters', sa.Integer(), nullable=False),
    sa.Column('energy_counters', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('is_tapped', sa.Boolean(), nullable=False),
    sa.Column('effective_power', sa.Integer(), nullable=True),
    sa.Column('effective_toughness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_card_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_card_id', sa.Integer(), nullable=False),
    sa.Column('counter_type', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_card_id'], ['zone_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_card_counters')
    op.drop_table('zone_cards')
    op.drop_table('turn_cards')
    op.drop_table('turn_actions')
    op.drop_table('board_states')
    op.drop_table('turns')
    op.drop_table('players')
    op.drop_table('notable_moments')
    op.drop_index(op.f('ix_games_video_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
